include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.icon.dart"
    - "**/*.part.dart"
    - "**/*.pbenum.dart"
    - "**/*.pb.dart"
    - "**/*.pbjson.dart"
    - "**/*.pbgrpc.dart"